services:
  db:
    image: postgres:16-alpine
    container_name: loanapi-db
    restart: always
    environment:
      POSTGRES_DB: loans
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d loans"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: loanapi-app
    ports:
      - "8080:8080"
    environment:
      # Usamos el nombre del servicio 'db' en lugar de localhost
      SPRING_DATASOURCE_URL: jdbc:postgresql://loanapi-db:5432/loans
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      db:
        condition: service_healthy
        restart: true