services:
  db:
    image: postgres:16-alpine
    container_name: loanapi-postgres
    restart: always
    environment:
      POSTGRES_DB: loans
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d loans"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: loanapi-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
